#Collecting player data v2


print("Hello player!")
print("")
print("To proceed, please enter your data below:")
print("Name:")
name = str(input())
print("")
print("Age:")
age = int(input())
print("")
print("Country of origin:")
origin = str(input())
print("")
print("Fluent languages:")
languages = str(input())
print("")
print("")
print("Thank you! Please confirm that this is your correct data, if it's wrong, restart the app")
print("")
print("")
print("")
print("Name:", name)
print("Age:", age)
print("Country:", origin)
print("Fluent in:", languages)